### ISSUE TITLE
`Pattern match(es) are non-exhaustive` error

### ISSUE THREAD

**Issue by RobertFischer** [dylex/postgresql-typed#13]
I am getting errors like this when I am using the `pgSQL` quasiquoter.

```sql
      INSERT INTO milestone_tasks (milestone_id,task_id)
      VALUES
      ( (SELECT ms.id FROM milestones ms WHERE ms.external_id = ${msId})
      , (SELECT t.id FROM tasks t WHERE t.external_id = ${taskId})
      )
      ON CONFLICT DO NOTHING
```
```
        Pattern match(es) are non-exhaustive
        In a lambda abstraction: Patterns not matched: _ (_:_)
```

```sql
      SELECT t.external_id
      FROM tasks t
      INNER JOIN milestone_tasks mt ON (mt.task_id = t.id)
      INNER JOIN milestones m ON (m.id = mt.milestone_id)
      WHERE m.external_id = ${msId}
      ORDER BY mt.ordering ASC
```
```
        Pattern match(es) are non-exhaustive
        In a lambda abstraction:
            Patterns not matched:
                _ []
                _ (_:_:_)
```

Any idea why this is being caused, or how to address it?

**Comment by dylex** [comment]
These are normally warnings, and even then often turned on, so I presume you're compiling with `-Wall -Werror` or similar. They should be safe to ignore (they're matching the result columns coming back from the database, so should always be the right number).  Just to avoid the warning, I've switched these matches to be irrefutable, which should be safe.

**Comment by RobertFischer** [comment]
It's part of `-Wall`, and I'm generally pretty sensitive to those particular errors, because it usually implies that I've changed a type that I've got a case statement over, so I need to handle a new case. Unfortunately, GHC doesn't give me a way to disable warnings for only part of a file. :(

Thanks for the change. I appreciate it!

**Comment by RobertFischer** [comment]
Still seeing this, even though I *should* be using your updated library. This is the relevant part of my `stack.yaml`: 

```yaml
flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- git: git@github.com:dylex/postgresql-typed.git
  commit: 734f8742f387bc8cc29d287fae72d8362d872007

compiler-check: newer-minor
resolver: lts-11.5
require-stack-version: ! '>=1.6'

flags:
    postgresql-binary:
        hdbc: false
```

But I'm still getting lots of warnings like these when -Wincomplete-uni-patterns is turned on:
```
        Pattern match(es) are non-exhaustive
        In a pattern binding:
            Patterns not matched:
                []
                (_:_:_)
        |
    471 |     qry id = [pgSQL|$ SELECT video_id FROM vimeo_sections WHERE id = ${id} |]
```
